import type { MetalRates, Product } from '@/types'

export const whatsappNumber = process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || '918849775545'

export const showroom = {
  name: 'SKKL Jewellers Heritage Salon',
  phone: '+91 97221 88559',
  email: 'concierge@skkljewellers.com',
  address: 'Shapur, Gujarat, India',
  hours: '09:30 AM - 8:00 PM, Sunday Closed',
  mapUrl: 'https://maps.google.com/?q=SKKL%20Jewellers%20Shapur%20Gujarat',
}

export const mockRates: MetalRates = {
  id: 'rates-2026-05-06',
  gold22k: 8725,
  gold24k: 9518,
  silver: 106,
  updatedAt: '2026-05-06T09:00:00+05:30',
  updatedBy: 'SKKL rates desk',
}

export const mockProducts: Product[] = [
  {
    id: 'skkl-bridal-001',
    name: 'Rajmata Polki Bridal Collar',
    slug: 'rajmata-polki-bridal-collar',
    category: 'bridal',
    images: [
      'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=85',
    ],
    weight: 86.4,
    price: 785000,
    showPrice: false,
    description: 'A ceremonial heirloom collar finished with hand-set polki, seed pearls, and warm 22K gold detailing.',
    tags: ['bridal', 'polki', 'heirloom'],
    occasion: ['wedding', 'festive'],
    material: '22K Gold, Polki, Pearls',
    purity: 'BIS Hallmarked 22K',
    inStock: true,
    featured: true,
    views: 4120,
  },
  {
    id: 'skkl-diamond-002',
    name: 'Noor Emerald Diamond Choker',
    slug: 'noor-emerald-diamond-choker',
    category: 'diamond',
    images: [
      'https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=1200&q=85',
    ],
    weight: 42.2,
    price: 525000,
    showPrice: false,
    description: 'A luminous diamond choker with emerald accents, designed for evening receptions and modern bridal styling.',
    tags: ['diamond', 'emerald', 'choker'],
    occasion: ['wedding', 'party'],
    material: '18K Gold, Emeralds, Diamonds',
    purity: '18K, IGI Certified Diamonds',
    inStock: true,
    featured: true,
    views: 3670,
  },
  {
    id: 'skkl-gold-003',
    name: 'Mysore Temple Kada Pair',
    slug: 'mysore-temple-kada-pair',
    category: 'gold',
    images: [
      'https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1619119069152-a2b331eb392a?auto=format&fit=crop&w=1200&q=85',
    ],
    weight: 58.8,
    price: 498000,
    showPrice: true,
    description: 'Sculptural temple kadas with antique relief work, mirror-polished borders, and a secure ceremonial clasp.',
    tags: ['gold', 'kada', 'temple'],
    occasion: ['wedding', 'festive'],
    material: '22K Gold',
    purity: 'BIS Hallmarked 22K',
    inStock: true,
    featured: true,
    views: 2980,
  },
  {
    id: 'skkl-kundan-004',
    name: 'Zarina Kundan Rani Haar',
    slug: 'zarina-kundan-rani-haar',
    category: 'kundan',
    images: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?auto=format&fit=crop&w=1200&q=85',
    ],
    weight: 74.5,
    price: 640000,
    showPrice: false,
    description: 'A regal long necklace with kundan setting, ruby enamel notes, and a graceful drape for heirloom wardrobes.',
    tags: ['kundan', 'rani haar', 'heritage'],
    occasion: ['wedding', 'festive'],
    material: '22K Gold, Kundan, Meenakari',
    purity: '22K',
    inStock: true,
    featured: true,
    views: 3310,
  },
  {
    id: 'skkl-platinum-005',
    name: 'Lumiere Platinum Solitaire',
    slug: 'lumiere-platinum-solitaire',
    category: 'platinum',
    images: [
      'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1589674781759-c21c37956a44?auto=format&fit=crop&w=1200&q=85',
    ],
    weight: 6.1,
    price: 310000,
    showPrice: true,
    description: 'A minimal platinum solitaire with a raised cathedral setting and exceptional brilliance under soft light.',
    tags: ['solitaire', 'platinum', 'engagement'],
    occasion: ['wedding', 'gifting'],
    material: '950 Platinum, Diamond',
    purity: 'VVS-EF Diamond',
    inStock: true,
    featured: false,
    views: 4460,
  },
  {
    id: 'skkl-silver-006',
    name: 'Chandni Silver Anklet Set',
    slug: 'chandni-silver-anklet-set',
    category: 'silver',
    images: [
      'https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1619119069152-a2b331eb392a?auto=format&fit=crop&w=1200&q=85',
    ],
    weight: 38.7,
    price: 14200,
    showPrice: true,
    description: 'A refined 925 silver anklet set with delicate ghungroo accents and a satin-polished finish.',
    tags: ['silver', 'anklet', 'daily wear'],
    occasion: ['daily-wear', 'gifting'],
    material: '925 Silver',
    purity: '92.5 Sterling Silver',
    inStock: true,
    featured: false,
    views: 1840,
  },
  {
    id: 'skkl-polki-007',
    name: 'Amara Polki Chandbali',
    slug: 'amara-polki-chandbali',
    category: 'polki',
    images: [
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1603974372039-adc49044b6bd?auto=format&fit=crop&w=1200&q=85',
    ],
    weight: 24.3,
    price: 255000,
    showPrice: false,
    description: 'Statement chandbalis with natural polki shimmer, pearl drops, and a comfortably balanced back chain.',
    tags: ['polki', 'earrings', 'chandbali'],
    occasion: ['festive', 'wedding'],
    material: '22K Gold, Polki, Pearls',
    purity: '22K',
    inStock: true,
    featured: true,
    views: 2890,
  },
  {
    id: 'skkl-gold-008',
    name: 'Aurelia Rose Gold Hoops',
    slug: 'aurelia-rose-gold-hoops',
    category: 'gold',
    images: [
      'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=1600&q=85',
      'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=1200&q=85',
    ],
    weight: 10.8,
    price: 92500,
    showPrice: true,
    description: 'Everyday rose gold hoops with a diamond-cut profile, designed to catch light with quiet confidence.',
    tags: ['gold', 'hoops', 'modern'],
    occasion: ['office', 'party', 'daily-wear'],
    material: '18K Rose Gold',
    purity: '18K',
    inStock: true,
    featured: true,
    views: 2110,
  },
]

export const categories = [
  { value: 'all', label: 'All' },
  { value: 'bridal', label: 'Bridal' },
  { value: 'diamond', label: 'Diamond' },
  { value: 'gold', label: 'Gold' },
  { value: 'kundan', label: 'Kundan' },
  { value: 'polki', label: 'Polki' },
  { value: 'platinum', label: 'Platinum' },
  { value: 'silver', label: 'Silver' },
] as const

export const formatPrice = (price?: number) =>
  typeof price === 'number' ? new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(price) : 'Price on request'

export const getWhatsappUrl = (message: string) =>
  `https://wa.me/${whatsappNumber}?text=${encodeURIComponent(message)}`
